version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: bookstore/app
    volumes:
     - .:/var/www/html
    ports:
     - "80:80"
    networks:
     - mynet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: bookstore/node
    volumes:
     - .:/var/www/html
    networks:
     - mynet
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bookstore"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - mynet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - mynet
networks:
  mynet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
